# Generated by Django 4.1.4 on 2023-02-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='NO Name', max_length=50)),
                ('customer_email', models.EmailField(default='No email', max_length=50)),
                ('customer_query', models.CharField(default='Query missing', max_length=300)),
                ('query_date', models.DateField()),
            ],
        ),
    ]
